# Generated by Django 4.0.7 on 2022-08-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='time_stamp',
            field=models.DateTimeField(default='2022-08-27T11:23:36.993048Z'),
        ),
    ]
