# Generated by Django 4.0.7 on 2022-08-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_poll_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
